services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=AbobaCorporations
      - DOCKER_INFLUXDB_INIT_BUCKET=Aboba
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=7G8_ZZsqKcNtM0B4p2_tYyps57EgfI6FCn0nMiHd4ydYbU6FLw1pe_qzbb7pO5hfRjn7DpTnhTPWz-ik8MebaQ==
    networks:
      - monitoring

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./logs:/var/log/app:ro
    depends_on:
      - influxdb
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - influxdb

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
